
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer ---------

{
  "title": "testi_uusin",
  "author": "testikirjailija_16",
  "url": "https://www.freecodecamp.org/news/how-to-deploy-a-nodejs-app-to-heroku-from-github-without-installing-heroku-on-your-machine-433bec770efe/",
  "likes": 0
}
